# Generated by Django 2.2.3 on 2019-07-08 11:18

import datetime
from django.db import migrations, models
import django.db.models.deletion
import doctors.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interests', models.BooleanField(default=False)),
                ('past_declarations', models.TextField(blank=True, null=True)),
                ('other_declarations', models.TextField(blank=True, null=True)),
                ('date_created', models.DateField(default=datetime.date.today)),
                ('dt_created', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='DeclarationLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('expires', models.DateTimeField(default=doctors.models.in_two_weeks)),
                ('key', models.CharField(default=doctors.models.random_token, max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gmc_number', models.CharField(max_length=100, unique=True)),
                ('job_title', models.CharField(max_length=200)),
                ('primary_employer', models.CharField(max_length=200)),
                ('employment_address', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PharmaBenefit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('reason', models.CharField(max_length=200)),
                ('band', models.IntegerField(choices=[(1, 'under £100'), (5, '£5000 - £10000'), (6, '£10000 - £50 000'), (7, '£50000- £100000'), (8, '£100000+')])),
                ('declaration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.Declaration')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.Doctor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OtherMedicalBenefit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('reason', models.CharField(max_length=200)),
                ('band', models.IntegerField(choices=[(1, 'under £100'), (5, '£5000 - £10000'), (6, '£10000 - £50 000'), (7, '£50000- £100000'), (8, '£100000+')])),
                ('declaration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.Declaration')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.Doctor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GrantBenefit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('reason', models.CharField(max_length=200)),
                ('band', models.IntegerField(choices=[(1, 'under £100'), (5, '£5000 - £10000'), (6, '£10000 - £50 000'), (7, '£50000- £100000'), (8, '£100000+')])),
                ('declaration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.Declaration')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.Doctor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeeBenefit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('reason', models.CharField(max_length=200)),
                ('band', models.IntegerField(choices=[(1, 'under £100'), (5, '£5000 - £10000'), (6, '£10000 - £50 000'), (7, '£50000- £100000'), (8, '£100000+')])),
                ('declaration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.Declaration')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.Doctor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='declaration',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.Doctor'),
        ),
    ]
