# Generated by Django 2.2.3 on 2019-07-05 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailedDeclaration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True)),
                ('for_year', models.IntegerField()),
                ('nothing_to_declare', models.BooleanField(default=False)),
                ('consultancy', models.BooleanField(default=False)),
                ('consultancy_band', models.CharField(blank=True, choices=[('under £100', 'under £100'), ('£100- £1000', '£100- £1000'), ('£1000- £2000', '£1000- £2000'), ('£2000 - £5000', '£2000 - £5000'), ('£5000 - £10000', '£5000 - £10000'), ('£10000 - £50 000', '£10000 - £50 000'), ('£50000- £100000', '£50000- £100000'), ('£100000+', '£100000+')], max_length=256, null=True, verbose_name='Band')),
                ('pharmaceutical_companies', models.BooleanField(default=False)),
                ('technology_companies', models.BooleanField(default=False)),
                ('consultancy_other', models.BooleanField(default=False, verbose_name='other')),
                ('consultancy_details', models.TextField(blank=True, verbose_name='details')),
                ('academic', models.BooleanField(default=False, verbose_name='academic_relationships')),
                ('academic_band', models.CharField(blank=True, choices=[('under £100', 'under £100'), ('£100- £1000', '£100- £1000'), ('£1000- £2000', '£1000- £2000'), ('£2000 - £5000', '£2000 - £5000'), ('£5000 - £10000', '£5000 - £10000'), ('£10000 - £50 000', '£10000 - £50 000'), ('£50000- £100000', '£50000- £100000'), ('£100000+', '£100000+')], max_length=256, null=True, verbose_name='Band')),
                ('research_grants', models.BooleanField(default=False)),
                ('academic_other', models.BooleanField(default=False)),
                ('academic_details', models.TextField(blank=True, verbose_name='details')),
                ('other_work', models.BooleanField(default=False)),
                ('other_work_band', models.CharField(blank=True, choices=[('under £100', 'under £100'), ('£100- £1000', '£100- £1000'), ('£1000- £2000', '£1000- £2000'), ('£2000 - £5000', '£2000 - £5000'), ('£5000 - £10000', '£5000 - £10000'), ('£10000 - £50 000', '£10000 - £50 000'), ('£50000- £100000', '£50000- £100000'), ('£100000+', '£100000+')], max_length=256, null=True, verbose_name='Band')),
                ('public_relations', models.BooleanField(default=False)),
                ('commercial_relationships', models.BooleanField(default=False)),
                ('media', models.BooleanField(default=False)),
                ('other_work_details', models.TextField(blank=True, verbose_name='details')),
                ('financial', models.BooleanField(default=False)),
                ('financial_band', models.CharField(blank=True, choices=[('under £100', 'under £100'), ('£100- £1000', '£100- £1000'), ('£1000- £2000', '£1000- £2000'), ('£2000 - £5000', '£2000 - £5000'), ('£5000 - £10000', '£5000 - £10000'), ('£10000 - £50 000', '£10000 - £50 000'), ('£50000- £100000', '£50000- £100000'), ('£100000+', '£100000+')], max_length=256, null=True, verbose_name='Band')),
                ('patents_owned', models.BooleanField(default=False, verbose_name='patents owned/part owned')),
                ('shares', models.BooleanField(default=False, verbose_name='shares/stocks/company ownership')),
                ('financial_details', models.TextField(blank=True, verbose_name='details')),
                ('spousal', models.BooleanField(default=False, verbose_name='spousal/family')),
                ('spousal_band', models.CharField(blank=True, choices=[('under £100', 'under £100'), ('£100- £1000', '£100- £1000'), ('£1000- £2000', '£1000- £2000'), ('£2000 - £5000', '£2000 - £5000'), ('£5000 - £10000', '£5000 - £10000'), ('£10000 - £50 000', '£10000 - £50 000'), ('£50000- £100000', '£50000- £100000'), ('£100000+', '£100000+')], max_length=256, null=True, verbose_name='Band')),
                ('spousal_details', models.TextField(blank=True, verbose_name='details')),
                ('sponsored', models.BooleanField(default=False, verbose_name='sponsored/educational events')),
                ('sponsored_band', models.CharField(blank=True, choices=[('under £100', 'under £100'), ('£100- £1000', '£100- £1000'), ('£1000- £2000', '£1000- £2000'), ('£2000 - £5000', '£2000 - £5000'), ('£5000 - £10000', '£5000 - £10000'), ('£10000 - £50 000', '£10000 - £50 000'), ('£50000- £100000', '£50000- £100000'), ('£100000+', '£100000+')], max_length=256, null=True, verbose_name='Band')),
                ('conferences', models.BooleanField(default=False)),
                ('meals', models.BooleanField(default=False, verbose_name='meals/hospitality/travel')),
                ('sponsored_details', models.TextField(blank=True, verbose_name='details')),
                ('political', models.BooleanField(default=False, verbose_name='political/membership organisations of note')),
                ('political_band', models.CharField(blank=True, choices=[('under £100', 'under £100'), ('£100- £1000', '£100- £1000'), ('£1000- £2000', '£1000- £2000'), ('£2000 - £5000', '£2000 - £5000'), ('£5000 - £10000', '£5000 - £10000'), ('£10000 - £50 000', '£10000 - £50 000'), ('£50000- £100000', '£50000- £100000'), ('£100000+', '£100000+')], max_length=256, null=True, verbose_name='Band')),
                ('political_details', models.TextField(blank=True, verbose_name='details')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.Doctor')),
            ],
            options={
                'ordering': ['-for_year', '-dt_created'],
            },
        ),
        migrations.CreateModel(
            name='WorkDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True)),
                ('position', models.CharField(choices=[('Academic', 'Academic'), ('NHS', 'NHS'), ('Private clinical work', 'Private clinical work')], max_length=256)),
                ('details', models.TextField(blank=True)),
                ('declaration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.DetailedDeclaration')),
            ],
        ),
    ]
