# Generated by Django 2.2.3 on 2019-07-07 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_detaileddeclaration_workdetails'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['-detaileddeclaration__dt_created', '-declaration__dt_created']},
        ),
    ]
