# Generated by Django 2.2.3 on 2019-07-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_detaileddeclaration_workdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workdetails',
            name='details',
        ),
        migrations.RemoveField(
            model_name='workdetails',
            name='position',
        ),
        migrations.AddField(
            model_name='workdetails',
            name='category',
            field=models.CharField(choices=[('Academic', 'Academic'), ('NHS', 'NHS'), ('Private clinical work', 'Private clinical work')], default='NHS', max_length=256, verbose_name='Position type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workdetails',
            name='institution',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='workdetails',
            name='job_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='gmc_number',
            field=models.CharField(max_length=100, unique=True, verbose_name='GMC Number'),
        ),
    ]
