# Generated by Django 2.2.3 on 2021-02-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_auto_20190709_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feebenefit',
            name='band',
            field=models.IntegerField(choices=[(1, 'under £100'), (2, '£100- £1000'), (3, '£1000- £2000'), (4, '£2000 - £5000'), (5, '£5000 - £10000'), (6, '£10000 - £50 000'), (7, '£50000- £100000'), (8, '£100000+')]),
        ),
        migrations.AlterField(
            model_name='grantbenefit',
            name='band',
            field=models.IntegerField(choices=[(1, 'under £100'), (2, '£100- £1000'), (3, '£1000- £2000'), (4, '£2000 - £5000'), (5, '£5000 - £10000'), (6, '£10000 - £50 000'), (7, '£50000- £100000'), (8, '£100000+')]),
        ),
        migrations.AlterField(
            model_name='othermedicalbenefit',
            name='band',
            field=models.IntegerField(choices=[(1, 'under £100'), (2, '£100- £1000'), (3, '£1000- £2000'), (4, '£2000 - £5000'), (5, '£5000 - £10000'), (6, '£10000 - £50 000'), (7, '£50000- £100000'), (8, '£100000+')]),
        ),
        migrations.AlterField(
            model_name='pharmabenefit',
            name='band',
            field=models.IntegerField(choices=[(1, 'under £100'), (2, '£100- £1000'), (3, '£1000- £2000'), (4, '£2000 - £5000'), (5, '£5000 - £10000'), (6, '£10000 - £50 000'), (7, '£50000- £100000'), (8, '£100000+')]),
        ),
    ]
